/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AffectedResultResponse {
  affectedProjects: Array<string>
}

/** Discover projects in a workspace (Nx or Turborepo) */
export declare function discoverProjects(cwd: string): Array<NapiProject>

/** Find affected projects in a monorepo */
export declare function findAffected(options: FindAffectedOptions): AffectedResultResponse

export interface FindAffectedOptions {
  cwd: string
  base: string
  rootTsConfig?: string
  projects: Array<NapiProject>
  include?: Array<string>
  ignoredPaths?: Array<string>
  enableProfiling?: boolean
}

export interface NapiProject {
  name: string
  sourceRoot: string
  tsConfig?: string
  implicitDependencies: Array<string>
  targets: Array<string>
}
